### ISSUE TITLE
(Re)survey gaps against azure ref arch functionality and open issues to cover their (re)implementation

### ISSUE THREAD

**Issue by jim-minter** [kargakis/acs-engine#24]
I'm guessing enabling the cloud provider functionality and storage are key ones among others?  Also plumbing through Azure service account credentials into the appropriate places?

**Comment by kargakis** [comment]
Registry storage setup:
https://docs.openshift.org/latest/install_config/storage_examples/azure_blob_docker_registry_example.html

And what the refarch is doing:
https://github.com/openshift/openshift-ansible-contrib/blob/3478284b4caecbf0184e6715237b3e839d4ffbab/reference-architecture/azure-ansible/3.7/bastion.sh#L1194-L1196
```shell
echo "setup registry for azure"
oc env dc docker-registry -e REGISTRY_STORAGE=azure -e REGISTRY_STORAGE_AZURE_ACCOUNTNAME=$REGISTRYSTORAGENAME -e REGISTRY_STORAGE_AZURE_ACCOUNTKEY=$REGISTRYKEY -e REGISTRY_STORAGE_AZURE_CONTAINER=registry
oc patch dc registry-console -p '{"spec":{"template":{"spec":{"nodeSelector":{"role":"infra"}}}}}'
```

**Comment by kargakis** [comment]
@jim-minter do we need this issue open anymore?

**Comment by kargakis** [comment]
Closing in favor of https://github.com/Azure/acs-engine/issues/2680
