### ISSUE TITLE
Enhance template disk setup

### ISSUE THREAD

**Issue by jim-minter** [kargakis/acs-engine#27]
Presumably we should be setting up multiple disks and one should be used for docker, as on other architectures?

**Comment by pweil-** [comment]
I believe this is not needed.  In the golden image we have multiple disks set up and your template uses the FromImage createOption.  That will result in 2 disks and the following physical volume setup:

```
[root@master 0]# pvs
  PV         VG        Fmt  Attr PSize    PFree
  /dev/sda2  rootvg    lvm2 a--    25.00g 1.00g
  /dev/sdc1  docker_vg lvm2 a--  <200.00g    0 
```

![pvs](https://user-images.githubusercontent.com/5230419/37536363-c2aad11a-2920-11e8-8e47-b65ee5bf157d.png)
