### ISSUE TITLE
Consider prebaking relevant docker images into golden images

### ISSUE THREAD

**Issue by jim-minter** [kargakis/acs-engine#29]
@kwoodson I'm probably putting this issue in the wrong place?

**Comment by kwoodson** [comment]
@jim-minter, probably.  What images specifically were you wanting to put in the image?

Possibilities:
- ose-deployer
- sti-builder
- ose-pod
- ose-docker-builder
- haproxy-router
- docker-registry

**Comment by jim-minter** [comment]
All of those and more.  At least everything relevant under registry.access.redhat.com/openshift3 ?

**Comment by jim-minter** [comment]
This is n/a as long as the golden image doesn't include a data disk.  Probably a nearby freestanding registry cache is more pragmatic than prebaking docker images into the vm

**Comment by kargakis** [comment]
Closing in favor of https://github.com/Azure/acs-engine/issues/2681
