### ISSUE TITLE
Add htpasswd support / non-hardcoded OCP password

### ISSUE THREAD

**Issue by jim-minter** [kargakis/acs-engine#32]

**Comment by kargakis** [comment]
@jim-minter can you add mire info here? Is this related to the webconsole?

**Comment by jim-minter** [comment]
at the moment the authentication is set up via htpasswd, which might possibly have hard coded credentials *cough*.  Should accept a username/password parameter, pipe it through into the htpasswd file that is laid down by certgen, maybe grant that user system:admin.

**Comment by jim-minter** [comment]
@glennswest please can you take a look at this issue today?
