### ISSUE TITLE
acs-engine should print template outputs at exit

### ISSUE THREAD

**Issue by jim-minter** [kargakis/acs-engine#34]
It'd be great if, instead of just printing "Finished ARM Deployment" at the end of a run, it printed the template outputs (like where to https / ssh to...)

**Comment by kargakis** [comment]
@jim-minter these kinds of issues should be better fixed upstream so we avoid some bikeshedding once we push our orchestrator.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/Azure/acs-engine/issues/2554

/close
