### ISSUE TITLE
Limit CSR auto-approver

### ISSUE THREAD

**Issue by kargakis** [kargakis/acs-engine#44]
Today the CSR auto-approver approves every open CSR. It needs to approve only those required for node bootstrapping.

https://github.com/openshift/origin/blob/master/contrib/kubernetes/static/sign.sh

@jim-minter

**Comment by pweil-** [comment]
https://github.com/openshift/openshift-ansible/blob/7e112b2c5893623dcd059813c993b0fab57e58b4/roles/openshift_bootstrap_autoapprover/files/openshift-bootstrap-controller.yaml

**Comment by pweil-** [comment]
see https://github.com/kargakis/acs-engine/pull/53#issuecomment-375429432
