### ISSUE TITLE
Review OpenShift Orchestrator for validation requirements

### ISSUE THREAD

**Issue by pweil-** [kargakis/acs-engine#76]
Many fields in the api like the new azure conf related fields are marked as `omitempty` but actually required for our OpenShift config.  We should add validation there to ensure we're failing fast.

**Comment by kargakis** [comment]
azure conf validation added in https://github.com/kargakis/acs-engine/pull/80

**Comment by kargakis** [comment]
availability profile validation added in https://github.com/kargakis/acs-engine/pull/83

**Comment by kargakis** [comment]
Closing in favor of https://github.com/Azure/acs-engine/issues/2688
